export const initialUserValues = {
    full_name: "",
    email: "",
    phone: "",
    country: "",
    city: "",
    state: "",
    zip_code: "",
    avatar: "",
    createdAt: "",
    updatedAt: "",
    is_verified: "",
    googleId: "",
    stripe_customer_id: "",
    alternate_email: "",
    alternate_phone: "",
    secret_question: "",
    secret_answer: "",
  };